### ISSUE TITLE
Request/Query

### ISSUE THREAD

**Issue by jshousephd** [hfang-bristol/XGR#6]
Love this product even more as time goes on. Fantastic work.

Is it possible to support parallel processing in xEnricherGenes() ?

**Comment by hfang-bristol** [comment]
Please use 'xEnricherGenesAdv' instead if you are to analyse many groups of genes (and/or many ontologies). Though not in parallel but it can speed up the analysis dramatically. Thank you for the interest.

**Comment by jshousephd** [comment]
I was trying to speed up the GOBP process itself. The `xEnricherGenesAdv` does not seem to matter in length of a test, but does return substantially less information about the run. 

Since that is single threaded, I'll just try to use doParallel to distribute 39 runs. 
Thank for the quick response!

**Comment by hfang-bristol** [comment]
Please do parallel in terms of pairs of a gene group + an ontology. In other words, for a given group of genes and an ontology specified, please do not run in parallel. Otherwise, there is an issue of how to calculate FDR. If there are many groups of genes to run, yes, please do parallel as you wish via xEnricherGenes().

**Comment by jshousephd** [comment]
Thanks for the response. I had 39 treatments that resulted in different identified differentially expressed gene sets.  I was parallelizing those 39 gene sets against a GOBP enrichment  for example.
This would be fine correct?

**Comment by hfang-bristol** [comment]
It works for what you have described.
